Error occurred while running 6stnd_4ch/1: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/1']' returned non-zero exit status 1.
Error occurred while running 6stnd_4ch/10: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/10']' returned non-zero exit status 1.
Error occurred while running 6stnd_4ch/11a: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/11a']' returned non-zero exit status 1.
Error occurred while running 6stnd_4ch/11b: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/11b']' returned non-zero exit status 1.
Error occurred while running 6stnd_4ch/12: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/12']' returned non-zero exit status 1.
Error occurred while running 6stnd_4ch/13: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/13']' returned non-zero exit status 1.
Error occurred while running 6stnd_4ch/14: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/14']' returned non-zero exit status 1.
Error occurred while running 6stnd_4ch/15: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/15']' returned non-zero exit status 1.
Error occurred while running 6stnd_4ch/16: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/16']' returned non-zero exit status 1.
File '17: log : [ERROR]:Something went wrong. Cannot determine GNP for verb k1 is missing.
File '18: log : [OK]:USR error. Main verb not identified. Check the USR.
File '19: log : [ERROR]:Something went wrong. Cannot determine GNP for verb k1 is missing.
Error occurred while running 6stnd_4ch/2: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/2']' returned non-zero exit status 1.
File '20: log : [OK]:USR error. Main verb not identified. Check the USR.
Error occurred while running 6stnd_4ch/21: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/21']' returned non-zero exit status 1.
Error occurred while running 6stnd_4ch/22a: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/22a']' returned non-zero exit status 1.
Error occurred while running 6stnd_4ch/22b: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/22b']' returned non-zero exit status 1.
File '23: log : [OK]:USR error. Main verb not identified. Check the USR.
Error occurred while running 6stnd_4ch/24a: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/24a']' returned non-zero exit status 1.
File '24b: log : [OK]:USR error. Main verb not identified. Check the USR.
Error occurred while running 6stnd_4ch/25a: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/25a']' returned non-zero exit status 1.
Error occurred while running 6stnd_4ch/25b: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/25b']' returned non-zero exit status 1.
Error occurred while running 6stnd_4ch/26a: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/26a']' returned non-zero exit status 1.
Error occurred while running 6stnd_4ch/26b: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/26b']' returned non-zero exit status 1.
Error occurred while running 6stnd_4ch/26c: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/26c']' returned non-zero exit status 1.
File '26d: log : [ERROR]:Something went wrong. Cannot determine GNP for verb k1 is missing.
Error occurred while running 6stnd_4ch/27a: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/27a']' returned non-zero exit status 1.
File '27b: log : [OK]:USR error. Main verb not identified. Check the USR.
Error occurred while running 6stnd_4ch/28a: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/28a']' returned non-zero exit status 1.
Error occurred while running 6stnd_4ch/28b: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/28b']' returned non-zero exit status 1.
File '29: log : [ERROR]:Something went wrong. Cannot determine GNP for verb k1 is missing.
Error occurred while running 6stnd_4ch/31b: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/31b']' returned non-zero exit status 1.
Error occurred while running 6stnd_4ch/31c: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/31c']' returned non-zero exit status 1.
File '31d: log : [ERROR]:Something went wrong. Cannot determine GNP for verb k1 is missing.
File '33: log : [OK]:USR error. Main verb not identified. Check the USR.
Error occurred while running 6stnd_4ch/34a: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/34a']' returned non-zero exit status 1.
File '34b: log : [OK]:USR error. Main verb not identified. Check the USR.
Error occurred while running 6stnd_4ch/35a: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/35a']' returned non-zero exit status 1.
Error occurred while running 6stnd_4ch/35b: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/35b']' returned non-zero exit status 1.
File '36: log : [OK]:USR error. Main verb not identified. Check the USR.
File '37: log : [ERROR]:Something went wrong. Cannot determine GNP for verb k1 is missing.
File '39: log : [ERROR]:Something went wrong. Cannot determine GNP for verb k1 is missing.
Error occurred while running 6stnd_4ch/3a: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/3a']' returned non-zero exit status 1.
Error occurred while running 6stnd_4ch/3b: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/3b']' returned non-zero exit status 1.
File '40: log : [OK]:USR error. Main verb not identified. Check the USR.
#मैं पृथ्वी के #एक #भाग पर #अपना #देश #राज्य #जिला #शहर #गाँव #अध्ययनकर #चाह #है |
File '4b: log : [OK]:USR error. Main verb not identified. Check the USR.
Error occurred while running 6stnd_4ch/5: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/5']' returned non-zero exit status 1.
Error occurred while running 6stnd_4ch/6: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/6']' returned non-zero exit status 1.
Error occurred while running 6stnd_4ch/7: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/7']' returned non-zero exit status 1.
Error occurred while running 6stnd_4ch/8: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/8']' returned non-zero exit status 1.
Error occurred while running 6stnd_4ch/9: Command '['python3', 'bulk_generate_input_modularize_new.py', '6stnd_4ch/9']' returned non-zero exit status 1.
